### ISSUE TITLE
Composer error finding package

### ISSUE THREAD

**Issue by arievanden** [pkpudev/yii2-gantt-widget#1]
I setup "pkpudev/yii2-gantt-widget": "*" in composer.json and run update. The error stated:
`The requested package pkpudev/yii2-gantt-widget could not be found in any version, there may be a typo in the package name.`

**Comment by zmiftah** [comment]
I am sorry, the package is still not on public yet

You could try adding this to your composer.json

    "repositories": {
       ...
       "pkpudev/yii2-gantt-widget" : {
            "type": "git",
            "url": "https://github.com/pkpudev/yii2-gantt-widget"
        },
       ...
    }

Hope this help
